"""create_Bus_Routs_table

Revision ID: 00750ce392fd
Revises: f939809ecd61
Create Date: 2022-11-23 21:03:10.886052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00750ce392fd'
down_revision = 'f939809ecd61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BusRoutes',
    sa.Column('bus_route_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bus_route_name', sa.String(), nullable=False),
    sa.Column('first_route', sa.String(), nullable=False),
    sa.Column('second_route', sa.String(), nullable=False),
    sa.Column('third_route', sa.String(), nullable=False),
    sa.Column('fourth_route', sa.String(), nullable=True),
    sa.Column('location_trip', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('bus_route_id')
    )
    op.create_index(op.f('ix_BusRoutes_bus_route_id'), 'BusRoutes', ['bus_route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_BusRoutes_bus_route_id'), table_name='BusRoutes')
    op.drop_table('BusRoutes')
    # ### end Alembic commands ###
