"""Edit Tutor Table

Revision ID: 01130a3937ad
Revises: 5386c055ffd6
Create Date: 2022-12-31 14:37:28.190651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01130a3937ad'
down_revision = '5386c055ffd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutors', 'year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutors', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
