"""delete club event table

Revision ID: 091b666a20a6
Revises: 13d91d771e14
Create Date: 2022-12-22 11:09:30.933113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091b666a20a6'
down_revision = '13d91d771e14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clubevents_club_event_id', table_name='clubevents')
    op.drop_table('clubevents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubevents',
    sa.Column('club_event_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('club_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Events.event_id'], name='clubevents_event_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('club_event_id', name='clubevents_pkey')
    )
    op.create_index('ix_clubevents_club_event_id', 'clubevents', ['club_event_id'], unique=False)
    # ### end Alembic commands ###
