"""edit Club Org

Revision ID: 0bddf964a5e5
Revises: e9ba09310653
Create Date: 2023-01-09 23:17:23.642625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bddf964a5e5'
down_revision = 'e9ba09310653'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ClubOrganizer_organizer_id_fkey', 'ClubOrganizer', type_='foreignkey')
    op.create_foreign_key(None, 'ClubOrganizer', 'Clubs', ['organizer_id'], ['club_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ClubOrganizer', type_='foreignkey')
    op.create_foreign_key('ClubOrganizer_organizer_id_fkey', 'ClubOrganizer', 'Organizers', ['organizer_id'], ['organizer_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
