"""Create Event Organizer

Revision ID: 13d91d771e14
Revises: ffd4d51684f4
Create Date: 2022-12-17 18:32:50.222719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d91d771e14'
down_revision = 'ffd4d51684f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EventOrganizer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Events.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizer_id'], ['Organizers.organizer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_EventOrganizer_id'), 'EventOrganizer', ['id'], unique=False)
    op.drop_constraint('Events_organizer_id_fkey', 'Events', type_='foreignkey')
    op.drop_column('Events', 'organizer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('organizer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Events_organizer_id_fkey', 'Events', 'Organizers', ['organizer_id'], ['organizer_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_EventOrganizer_id'), table_name='EventOrganizer')
    op.drop_table('EventOrganizer')
    # ### end Alembic commands ###
