"""create_Course_Table

Revision ID: 16302df9b8a6
Revises: a7be20330b9b
Create Date: 2022-11-29 20:51:28.697694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16302df9b8a6'
down_revision = 'a7be20330b9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('college', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'college')
    # ### end Alembic commands ###
