"""Create_Table_Session_Enrolled

Revision ID: 1b8702bf5583
Revises: e217b76aa619
Create Date: 2022-12-12 11:52:21.157733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8702bf5583'
down_revision = 'e217b76aa619'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessionEnrolled',
    sa.Column('enroll_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sessionId', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sessionId'], ['courseSessions.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enroll_id')
    )
    op.create_index(op.f('ix_sessionEnrolled_enroll_id'), 'sessionEnrolled', ['enroll_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessionEnrolled_enroll_id'), table_name='sessionEnrolled')
    op.drop_table('sessionEnrolled')
    # ### end Alembic commands ###
