"""edit call logs date and time

Revision ID: 1e6845730381
Revises: 0bddf964a5e5
Create Date: 2023-01-14 16:54:41.864696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6845730381'
down_revision = '0bddf964a5e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CallLogsStudent', sa.Column('datetime', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CallLogsStudent', 'datetime')
    # ### end Alembic commands ###
