"""create_Organizers_table

Revision ID: 20a92eaca38d
Revises: 5fa253cfb805
Create Date: 2022-11-23 21:02:40.913589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a92eaca38d'
down_revision = '5fa253cfb805'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Organizers',
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('organizer_name', sa.String(), nullable=False),
    sa.Column('organizer_image', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organizer_id')
    )
    op.create_index(op.f('ix_Organizers_organizer_id'), 'Organizers', ['organizer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Organizers_organizer_id'), table_name='Organizers')
    op.drop_table('Organizers')
    # ### end Alembic commands ###
