"""Create_permit_holders_table

Revision ID: 25a592a69b83
Revises: f155ef388c25
Create Date: 2022-12-09 11:14:50.908819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a592a69b83'
down_revision = 'f155ef388c25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permitHolders',
    sa.Column('permit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_owner_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('car_color', sa.String(), nullable=False),
    sa.Column('car_type', sa.String(), nullable=False),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('permit_number', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permit_id')
    )
    op.create_index(op.f('ix_permitHolders_permit_id'), 'permitHolders', ['permit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permitHolders_permit_id'), table_name='permitHolders')
    op.drop_table('permitHolders')
    # ### end Alembic commands ###
