"""create_Tutor_Request_Table

Revision ID: 2a16043cce37
Revises: 954c90c73c62
Create Date: 2022-12-05 18:09:30.027661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a16043cce37'
down_revision = '954c90c73c62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutorsRequests',
    sa.Column('tutor_request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('semester_completion', sa.String(), nullable=False),
    sa.Column('grade', sa.Float(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tutor_request_id')
    )
    op.create_index(op.f('ix_tutorsRequests_tutor_request_id'), 'tutorsRequests', ['tutor_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutorsRequests_tutor_request_id'), table_name='tutorsRequests')
    op.drop_table('tutorsRequests')
    # ### end Alembic commands ###
