"""Create_Bus_Routes_table

Revision ID: 31a73e0df269
Revises: 2c8dacd200fb
Create Date: 2022-12-09 10:40:22.859788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a73e0df269'
down_revision = '2c8dacd200fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BusRoutes',
    sa.Column('bus_route_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bus_route_name', sa.String(), nullable=False),
    sa.Column('first_route', sa.String(), nullable=False),
    sa.Column('second_route', sa.String(), nullable=False),
    sa.Column('third_route', sa.String(), nullable=False),
    sa.Column('fourth_route', sa.String(), nullable=True),
    sa.Column('location_trip', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('bus_route_id')
    )
    op.create_index(op.f('ix_BusRoutes_bus_route_id'), 'BusRoutes', ['bus_route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_BusRoutes_bus_route_id'), table_name='BusRoutes')
    op.drop_table('BusRoutes')
    # ### end Alembic commands ###
