"""create_Course_Tutor_Table

Revision ID: 32acbcfd592d
Revises: 16302df9b8a6
Create Date: 2022-11-29 20:53:00.905844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32acbcfd592d'
down_revision = '16302df9b8a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coursesTutors',
    sa.Column('ct_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.tutor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ct_id')
    )
    op.create_index(op.f('ix_coursesTutors_ct_id'), 'coursesTutors', ['ct_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coursesTutors_ct_id'), table_name='coursesTutors')
    op.drop_table('coursesTutors')
    # ### end Alembic commands ###
