"""Create_CSO_Events_table

Revision ID: 53040250cc55
Revises: 911387fe1749
Create Date: 2022-12-09 10:41:00.320237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53040250cc55'
down_revision = '911387fe1749'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csoevents',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('supervisor', sa.String(), nullable=False),
    sa.Column('hours_credit', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_csoevents_event_id'), 'csoevents', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_csoevents_event_id'), table_name='csoevents')
    op.drop_table('csoevents')
    # ### end Alembic commands ###
