"""Create BusRouteImages Table

Revision ID: 5386c055ffd6
Revises: e47b86430bca
Create Date: 2022-12-29 12:59:45.851336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5386c055ffd6'
down_revision = 'e47b86430bca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('busRouteImages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('ramadan_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_busRouteImages_id'), 'busRouteImages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_busRouteImages_id'), table_name='busRouteImages')
    op.drop_table('busRouteImages')
    # ### end Alembic commands ###
