"""Alter_Course_Session_table_Add_StdID

Revision ID: 73a718710c3e
Revises: 25a592a69b83
Create Date: 2022-12-12 11:13:13.886194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a718710c3e'
down_revision = '25a592a69b83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courseSessions', sa.Column('student_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courseSessions', 'students', ['student_id'], ['student_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courseSessions', type_='foreignkey')
    op.drop_column('courseSessions', 'student_id')
    # ### end Alembic commands ###
