"""create_Club_Events_table

Revision ID: 767e4b3f085e
Revises: 586eec4bc5d3
Create Date: 2022-11-23 21:03:38.976306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767e4b3f085e'
down_revision = '586eec4bc5d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubevents',
    sa.Column('club_event_id', sa.Integer(), nullable=False),
    sa.Column('club_name', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('club_event_id')
    )
    op.create_index(op.f('ix_clubevents_club_event_id'), 'clubevents', ['club_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clubevents_club_event_id'), table_name='clubevents')
    op.drop_table('clubevents')
    # ### end Alembic commands ###
