"""Create club organizer

Revision ID: 7817c5886e0f
Revises: 9a68e6fd9f84
Create Date: 2023-01-01 12:27:56.940435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7817c5886e0f'
down_revision = '9a68e6fd9f84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ClubOrganizer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Events.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizer_id'], ['Organizers.organizer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ClubOrganizer_id'), 'ClubOrganizer', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ClubOrganizer_id'), table_name='ClubOrganizer')
    op.drop_table('ClubOrganizer')
    # ### end Alembic commands ###
