"""Create_Organnizers_table

Revision ID: 7c28007ac853
Revises: 74b9613a828a
Create Date: 2022-12-09 10:40:00.774684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c28007ac853'
down_revision = '74b9613a828a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Organizers',
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('organizer_name', sa.String(), nullable=False),
    sa.Column('organizer_image', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organizer_id')
    )
    op.create_index(op.f('ix_Organizers_organizer_id'), 'Organizers', ['organizer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Organizers_organizer_id'), table_name='Organizers')
    op.drop_table('Organizers')
    # ### end Alembic commands ###
