"""Edit Tutor Table

Revision ID: 9a68e6fd9f84
Revises: 094104abb217
Create Date: 2022-12-31 15:16:29.430898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a68e6fd9f84'
down_revision = '094104abb217'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutors', 'gpa')
    op.drop_column('tutors', 'tutor_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutors', sa.Column('tutor_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tutors', sa.Column('gpa', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
