"""Create_Students_Images_Table

Revision ID: 9b2d180289fc
Revises: cd2edfdf4ce1
Create Date: 2022-10-22 17:45:49.588384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b2d180289fc'
down_revision = 'cd2edfdf4ce1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentImages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagePath', sa.String(), nullable=False),
    sa.Column('imageName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentImages')
    # ### end Alembic commands ###
