"""Create Course Requests Table

Revision ID: a8df0d6c505e
Revises: c924d2a93606
Create Date: 2022-12-23 20:19:55.889817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8df0d6c505e'
down_revision = 'c924d2a93606'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coursesRequests',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_coursesRequests_request_id'), 'coursesRequests', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coursesRequests_request_id'), table_name='coursesRequests')
    op.drop_table('coursesRequests')
    # ### end Alembic commands ###
