"""create_CSO_Events_Table

Revision ID: b01e601b1358
Revises: 767e4b3f085e
Create Date: 2022-11-28 10:44:51.004071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01e601b1358'
down_revision = '767e4b3f085e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csoevents',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('supervisor', sa.String(), nullable=False),
    sa.Column('hours_credit', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_csoevents_event_id'), 'csoevents', ['event_id'], unique=False)
    op.create_table('clubevents',
    sa.Column('club_event_id', sa.Integer(), nullable=False),
    sa.Column('club_name', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('club_event_id')
    )
    op.create_index(op.f('ix_clubevents_club_event_id'), 'clubevents', ['club_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clubevents_club_event_id'), table_name='clubevents')
    op.drop_table('clubevents')
    op.drop_index(op.f('ix_csoevents_event_id'), table_name='csoevents')
    op.drop_table('csoevents')
    # ### end Alembic commands ###
