"""Create Club Events Table

Revision ID: c924d2a93606
Revises: 091b666a20a6
Create Date: 2022-12-22 12:20:29.797623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c924d2a93606'
down_revision = '091b666a20a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Clubs_club_id', table_name='Clubs')
    op.create_index(op.f('ix_Clubs_club_id'), 'Clubs', ['club_id'], unique=True)
    op.alter_column('clubevents', 'club_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'clubevents', 'Clubs', ['club_id'], ['club_id'], ondelete='CASCADE')
    op.drop_column('clubevents', 'club_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubevents', sa.Column('club_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'clubevents', type_='foreignkey')
    op.alter_column('clubevents', 'club_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_Clubs_club_id'), table_name='Clubs')
    op.create_index('ix_Clubs_club_id', 'Clubs', ['club_id'], unique=False)
    # ### end Alembic commands ###
