"""Create_CSO_Events_Attended_table

Revision ID: caf872a2f622
Revises: 53040250cc55
Create Date: 2022-12-09 10:41:12.121638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf872a2f622'
down_revision = '53040250cc55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csoeventsattended',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Events.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csoeventsattended_id'), 'csoeventsattended', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_csoeventsattended_id'), table_name='csoeventsattended')
    op.drop_table('csoeventsattended')
    # ### end Alembic commands ###
