"""Swap_Organizer_Foregin_Key

Revision ID: d147ecbaf10b
Revises: 1b8702bf5583
Create Date: 2022-12-17 17:56:32.074226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd147ecbaf10b'
down_revision = '1b8702bf5583'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('organizer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Events', 'Organizers', ['organizer_id'], ['organizer_id'], ondelete='CASCADE')
    op.drop_constraint('Organizers_event_id_fkey', 'Organizers', type_='foreignkey')
    op.drop_column('Organizers', 'event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Organizers', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Organizers_event_id_fkey', 'Organizers', 'Events', ['event_id'], ['event_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'Events', type_='foreignkey')
    op.drop_column('Events', 'organizer_id')
    # ### end Alembic commands ###
