"""create_CSO_Events_Attended_Table

Revision ID: df5fd5d2e091
Revises: b01e601b1358
Create Date: 2022-11-28 10:45:39.448901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5fd5d2e091'
down_revision = 'b01e601b1358'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csoeventsattended',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Events.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csoeventsattended_id'), 'csoeventsattended', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_csoeventsattended_id'), table_name='csoeventsattended')
    op.drop_table('csoeventsattended')
    # ### end Alembic commands ###
