"""create_Students_Images_table

Revision ID: e33ee485b95f
Revises: f5f6c0d4202d
Create Date: 2022-11-23 21:02:06.958235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33ee485b95f'
down_revision = 'f5f6c0d4202d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentImages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagePath', sa.String(), nullable=False),
    sa.Column('imageName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentImages')
    # ### end Alembic commands ###
