"""Create BusRoute Table

Revision ID: e47b86430bca
Revises: 0ca66c9da298
Create Date: 2022-12-25 21:31:32.926355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47b86430bca'
down_revision = '0ca66c9da298'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BusRoutes',
    sa.Column('bus_route_id', sa.Integer(), nullable=False),
    sa.Column('mon_wed_back', sa.Integer(), nullable=True),
    sa.Column('mon_wed_presence', sa.Integer(), nullable=True),
    sa.Column('sun_tue_thu_back', sa.Integer(), nullable=True),
    sa.Column('sun_tue_thu_presence', sa.Integer(), nullable=True),
    sa.Column('pickup_dropoff', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bus_route_id')
    )
    op.create_index(op.f('ix_BusRoutes_bus_route_id'), 'BusRoutes', ['bus_route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_BusRoutes_bus_route_id'), table_name='BusRoutes')
    op.drop_table('BusRoutes')
    # ### end Alembic commands ###
