"""Create_Organizers_Table

Revision ID: e906c4424544
Revises: 61111895d2f6
Create Date: 2022-10-22 21:16:26.009905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e906c4424544'
down_revision = '61111895d2f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Organizers',
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('organizer_name', sa.String(), nullable=False),
    sa.Column('organizer_image', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Events.event_id'], ),
    sa.PrimaryKeyConstraint('organizer_id')
    )
    op.create_index(op.f('ix_Organizers_organizer_id'), 'Organizers', ['organizer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Organizers_organizer_id'), table_name='Organizers')
    op.drop_table('Organizers')
    # ### end Alembic commands ###
