"""Create_Tutor_Requests_table

Revision ID: f155ef388c25
Revises: 68b2ea5203b7
Create Date: 2022-12-09 10:42:14.146036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f155ef388c25'
down_revision = '68b2ea5203b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutorsRequests',
    sa.Column('tutor_request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('semester_completion', sa.String(), nullable=False),
    sa.Column('grade', sa.Float(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tutor_request_id')
    )
    op.create_index(op.f('ix_tutorsRequests_tutor_request_id'), 'tutorsRequests', ['tutor_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutorsRequests_tutor_request_id'), table_name='tutorsRequests')
    op.drop_table('tutorsRequests')
    # ### end Alembic commands ###
