"""Edit Course Session Table

Revision ID: ff6791101179
Revises: 7817c5886e0f
Create Date: 2023-01-01 19:40:17.340069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff6791101179'
down_revision = '7817c5886e0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courseSessions', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('courseSessions', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('courseSessions', 'day',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('courseSessions_student_id_fkey', 'courseSessions', type_='foreignkey')
    op.drop_column('courseSessions', 'student_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courseSessions', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('courseSessions_student_id_fkey', 'courseSessions', 'students', ['student_id'], ['student_id'], ondelete='CASCADE')
    op.alter_column('courseSessions', 'day',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('courseSessions', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('courseSessions', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###
