"""Swap_Organizer_Foregin_Key2

Revision ID: ffd4d51684f4
Revises: d147ecbaf10b
Create Date: 2022-12-17 18:00:50.092024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd4d51684f4'
down_revision = 'd147ecbaf10b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Events', 'organizer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Events', 'organizer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
